version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    command: >
      bash -c "composer install
      && php artisan serve --host=0.0.0.0 --port=80"
